### ISSUE TITLE
error when running echo example

### ISSUE THREAD

**Issue by mikaelkaron** [Stackvana/microservice-examples#1]
When running the echo example I get this error in the browser:

```
node.js:707
          throw new Error('Implement me. Unknown stdin file type!');
          ^

Error: Implement me. Unknown stdin file type!
    at process.stdin (node.js:707:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/microcule/bin/binaries/node:214:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

Running this inside an ubuntu bash shell on win 10 (not sure if that matters)

**Comment by Marak** [comment]
@mikaelkaron - 

What happens if you download https://github.com/stackvana/microcule and run the tests?

What version of node are you running?

**Comment by mikaelkaron** [comment]
here's the output from ubuntu-bash-on-windows: [stdout.txt](https://github.com/Stackvana/microservice-examples/files/561565/stdout.txt) with node-v4.2.6

And here from the same machine but through powershell: [stdout.txt](https://github.com/Stackvana/microservice-examples/files/561566/stdout.txt) with node-v7.0.0

**Comment by Marak** [comment]
@mikaelkaron -

I think this is a simple cross-platform path issue in `microcule`.

I should be able to fix this quickly and publish a new release shortly.

Will update issue when I have more information or a fix.

**Comment by Marak** [comment]
@mikaelkaron -

I pushed a new version of microcule: `microcule@4.0.2`

Can you update to this version and try again?

I'm unable to test windows here or on travis, but I _think_ this should fix it.

Related commit: https://github.com/Stackvana/microcule/commit/0f1cc6f06f45d7e182732693ed4f4d5a52d4f0f4

**Comment by mikaelkaron** [comment]
[stdout.bash.txt](https://github.com/Stackvana/microservice-examples/files/563721/stdout.bash.txt)
[stdout.cmd.txt](https://github.com/Stackvana/microservice-examples/files/563722/stdout.cmd.txt)

new output new error.

**Comment by mikaelkaron** [comment]
I'm on GMT+1 if you want to try some live debug one of these days, just ping me here. Thanks for the awesome software (well, I'm imagining it being awesome once I can get it to run on my dev system) but at least in my head I'm already thinking of how this would help me deploy (and combine!) our internal services.

**Comment by mikaelkaron** [comment]
I tried to dig into it and at least in the cmd environment it looks like it won't spawn the `node` binary. I think this could actually be a windows thing where we may have to have a `node.cmd` that wraps `node` as we don't really have an executable bit to put directly on what we spawn.

Now we have to handle this when we spawn as on windows we'd need to spawn the cmd, but on other platforms (with executable bit) we'd like to exec directly.

Thoughts?

**Comment by mikaelkaron** [comment]
Maybe something like https://github.com/IndigoUnited/node-cross-spawn could be the solution?

**Comment by mikaelkaron** [comment]
Added PR Stackvana/microcule#11 that takes care of part of the issue (actually spawning the process). 

After that patch this is now the test results:

[stdout.bash.txt](https://github.com/Stackvana/microservice-examples/files/564110/stdout.bash.txt)
[stdout.cmd.txt](https://github.com/Stackvana/microservice-examples/files/564111/stdout.cmd.txt)

So that may actually make sense.
- The bash terminal in window is a special beast and I won't be surprised if it messes with `process.stdout` (thus resulting in the bash related errors).
- And not having `sh` around in the cmd environment is quite expected.

Closing. Issue fixed in related PR.
